/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author imamovicdze
 */

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

public class Home extends javax.swing.JFrame {
    
    private ImageIcon format = null;
    String filename = null;
    byte[] person_image = null;
    private String gender;
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form Home
     */
    
    public Home() {
        
        initComponents();
        conn = Connect.getCon();
        CurrentDate();
        Update();
        
    }
    
    public final void Update() {
        
        try {
            
            String sql = "SELECT id, name, age, gender, department, shift, division FROM user_info";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        } finally {
            
            try {
                
                rs.close();
                pst.close();
                
            } catch (SQLException e) {
                
            }
        }
    }
    
    public final void CurrentDate() {
        
        Thread clock;
        
        clock = new Thread() {
            
            public void run() {
                
                for(;;) {
                    
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    
                    menu_date.setText("Date: " + day + "-" + (month+1) + "-" + year);
                    
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    
                    menu_time.setText("Time: " + hour + ":" + (min) + ":" + sec);
                    
                    try {
                        
                        sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                        
                    }
                }
            }
        };
        
        clock.start();
        
    }
    
    public void setMaleGender() {
        
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
        
    }
    
    public void setFemaleGender() {
        
        gender = "Female";
        r_female.setSelected(true);
        r_male.setSelected(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_age = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        txt_shift = new javax.swing.JTextField();
        txt_gp = new javax.swing.JTextField();
        lbl_department = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        lbl_gp = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        lbl_shift = new javax.swing.JLabel();
        lbl_division = new javax.swing.JLabel();
        txt_division = new javax.swing.JTextField();
        lbl_surname = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        c_age = new javax.swing.JComboBox<>();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        btn_print = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_welcome = new javax.swing.JLabel();
        lbl_welcome1 = new javax.swing.JLabel();
        btn_attach = new javax.swing.JButton();
        lbl_persons = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_show = new javax.swing.JButton();
        txt_count = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_search = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_item_exit = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();
        menu_item_faq = new javax.swing.JMenuItem();
        menu_date = new javax.swing.JMenu();
        menu_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employees.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Person Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        lbl_age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_age.setText("Age");

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(204, 204, 204));

        lbl_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_id.setText("Id");

        lbl_gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_gender.setText("Gender");

        txt_shift.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_shiftKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_shiftKeyTyped(evt);
            }
        });

        txt_gp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_gpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_gpKeyTyped(evt);
            }
        });

        lbl_department.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_department.setText("Department");

        txt_department.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_departmentKeyPressed(evt);
            }
        });

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });

        lbl_gp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_gp.setText("GP");

        txt_surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_surnameKeyPressed(evt);
            }
        });

        lbl_shift.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_shift.setText("Shift");

        lbl_division.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_division.setText("Division");

        txt_division.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_divisionKeyPressed(evt);
            }
        });

        lbl_surname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_surname.setText("Surname");

        lbl_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_name.setText("Name");

        c_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "45", "46", "47", "48", "49", "50" }));
        c_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ageActionPerformed(evt);
            }
        });

        buttonGroup1.add(r_male);
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(r_female);
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(lbl_shift)
                    .addComponent(lbl_gender)
                    .addComponent(lbl_department)
                    .addComponent(lbl_name)
                    .addComponent(lbl_surname)
                    .addComponent(lbl_gp)
                    .addComponent(lbl_age)
                    .addComponent(lbl_division))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_division, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(txt_gp)
                        .addComponent(txt_shift)
                        .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r_male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_female)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_surname)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_age)
                    .addComponent(c_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r_female, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_male, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_shift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbl_gender)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_department)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_shift)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_gp)
                    .addComponent(txt_gp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_division))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print-icon.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-icon.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil-icon.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Close-icon.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-edit-clear-icon.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_save)
                .addGap(18, 18, 18)
                .addComponent(btn_delete)
                .addGap(13, 13, 13)
                .addComponent(btn_update)
                .addGap(18, 18, 18)
                .addComponent(btn_clear)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lbl_welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_welcome.setText("Welcome to Management System");

        lbl_welcome1.setText("Easily manage with your directory");

        btn_attach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Editing-Attach-icon.png"))); // NOI18N
        btn_attach.setText("Attach image");
        btn_attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attachActionPerformed(evt);
            }
        });

        lbl_persons.setText("Total Persons");

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-Interface-Logout-icon.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eye-2-icon.png"))); // NOI18N
        btn_show.setText("Show");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });

        txt_count.setEditable(false);
        txt_count.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 102, 153))); // NOI18N

        lbl_search.setText("Search Name");

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbl_search)
                .addGap(18, 18, 18)
                .addComponent(txt_search)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_search)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img.png"))); // NOI18N

        menu_file.setText("File");

        menu_item_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-dialog-cancel-icon.png"))); // NOI18N
        menu_item_exit.setText("Exit");
        menu_item_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_exitActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_exit);

        jMenuBar1.add(menu_file);

        menu_help.setText("Help");

        menu_item_faq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FAQ-icon.png"))); // NOI18N
        menu_item_faq.setText("FAQ");
        menu_item_faq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_faqActionPerformed(evt);
            }
        });
        menu_help.add(menu_item_faq);

        jMenuBar1.add(menu_help);

        menu_date.setText("Date");
        jMenuBar1.add(menu_date);

        menu_time.setText("Time");
        jMenuBar1.add(menu_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_logo)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_welcome)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbl_welcome1)))
                        .addGap(32, 32, 32)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_attach)
                        .addGap(199, 199, 199)
                        .addComponent(lbl_persons)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_count)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_show))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btn_logout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lbl_welcome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_welcome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_logout)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(image))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_show)
                                    .addComponent(txt_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_persons)
                                    .addComponent(btn_attach))
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_print))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        setSize(new java.awt.Dimension(1200, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
      
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try {
            
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
            
        } catch (PrinterException e) {
            
            System.err.format("Cannot Print %s%n", e.getMessage());
            
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
       
        try {
            
            dispose();
            new Login().setVisible(true);
            
        } finally {
            
            try {
                
                rs.close();
                pst.close();
                
            } catch (SQLException e) {
            
            }
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void menu_item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_exitActionPerformed
       
        System.exit(0);
        
    }//GEN-LAST:event_menu_item_exitActionPerformed

    private void menu_item_faqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_faqActionPerformed
       
        try {
            
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\Admin\\Documents\\NetBeansProjects\\javamanagementsystem\\about_software.pdf");
            
        } catch (IOException e) {
            
            JOptionPane.showMessageDialog(null, "Error");
            
        }
    }//GEN-LAST:event_menu_item_faqActionPerformed

    private void btn_attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attachActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        
        File file_upload = chooser.getSelectedFile();
        filename = file_upload.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance (image.getWidth(), image.getHeight(), Image.SCALE_DEFAULT));
        image.setIcon(imageIcon);
        
        try {
            
            File image_stream_upload = new File(filename);
            FileInputStream fis = new FileInputStream(image_stream_upload);
            
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            
            for (int number; ( number = fis.read(buffer)) != - 1; ) { 
                
                baos.write(buffer, 0, number);
                
            }
            
            person_image = baos.toByteArray();
            
        } catch (IOException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        finally {
            
            try {
                
                rs.close();
                pst.close();
                
            } catch (SQLException e) {
                
            }
        }
    }//GEN-LAST:event_btn_attachActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        if (txt_name.getText().isEmpty()) {
            
            txt_name.requestFocus();
            
        } else if (txt_surname.getText().isEmpty()) {
            
            txt_surname.requestFocus();
            
        } else if (txt_department.getText().isEmpty()) {
            
            txt_department.requestFocus();
            
        } else if (txt_shift.getText().isEmpty()) {
            
            txt_shift.requestFocus();
            
        } else if (txt_gp.getText().isEmpty()) {
            
            txt_gp.requestFocus();
            
        } else if (txt_division.getText().isEmpty()) {
            
            txt_division.requestFocus();
            
        } else {
            
            int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this person?" , 
                    "Adding employee", JOptionPane.YES_NO_OPTION);

            if (x == 0) {

                try {

                    String sql = "INSERT INTO user_info (name, surname, age, image, gender, "
                            + "department, shift, emploee_egp, division) VALUES (?,?,?,?,?,?,?,?,?)";

                    pst = conn.prepareStatement(sql);

                    pst.setString(1, txt_name.getText());
                    pst.setString(2, txt_surname.getText());

                    String stringAge = c_age.getSelectedItem().toString();
                    int intAge = Integer.parseInt(stringAge);
                    pst.setInt(3, intAge);

                    pst.setBytes(4, person_image);
                    pst.setString(5, gender);
                    pst.setString(6, txt_department.getText());
                    pst.setString(7, txt_shift.getText());
                    pst.setString(8, txt_gp.getText());
                    pst.setString(9, txt_division.getText());

                    pst.execute();

                    JOptionPane.showMessageDialog(null, "Data is saved successfully");

                } catch (HeadlessException | NumberFormatException | SQLException e) {

                    JOptionPane.showMessageDialog(null, e);

                }

                finally {

                    try {

                        rs.close();
                        pst.close();

                    } catch (SQLException e) {  

                    }   
                }
            }
        }
        
        Update();
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
      
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this person?", "Delete employee", JOptionPane.YES_NO_OPTION);
        
        if (p == 0) {
            
            String sql = "DELETE FROM user_info WHERE id = ?";
            
            try {
                
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_id.getText());
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Successfully Deleted!");
                
            } catch (HeadlessException | SQLException e) {
                
                JOptionPane.showMessageDialog(null, e);
                
            }
        }
        
        Update();
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        int row = jTable1.getSelectedRow();
        
        String table_click = (jTable1.getModel().getValueAt(row, 0).toString());
        
        try {
            
            String sql = "SELECT image FROM user_info WHERE id ='" + table_click + "'";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                
                byte[]imagedata = rs.getBytes("image");
                format = new ImageIcon(imagedata);
                image.setIcon(format);
                
            }
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        try {
            
            String sql = "SELECT * FROM user_info WHERE id ='" + table_click + "'";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                
                String add8 = rs.getString("id");
                txt_id.setEditable(false);
                txt_id.setBackground(Color.lightGray);
                txt_id.setText(add8);
                
                String add1 = rs.getString("name");
                txt_name.setText(add1);
                
                String add2 = rs.getString("surname");
                txt_surname.setText(add2);
                
                String add4 = rs.getString("department");
                txt_department.setText(add4);
                
                String add9 = rs.getString("gender");
                if(add9.equals("Male")) {
                
                this.setMaleGender();

                } else {
                    
                this.setFemaleGender();
                   
                }
                
                String add10 = rs.getString("age");
                c_age.setSelectedItem(add10);
              
                String add5 = rs.getString("shift");
                txt_shift.setText(add5);
                
                String add6 = rs.getString("emploee_egp");
                txt_gp.setText(add6);
                
                String add7 = rs.getString("division");
                txt_division.setText(add7);
                
            }
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
       
        String val1 = txt_id.getText();
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update person data?", "Update User", JOptionPane.YES_NO_OPTION);
        
        if (x == 0) {
            try {
                
                String val2 = txt_name.getText();
                String val3 = txt_surname.getText();
                String val4 = txt_department.getText();
                String val5 = txt_shift.getText();
                String val6 = txt_gp.getText();
                String val7 = txt_division.getText();
                String stringAge = c_age.getSelectedItem().toString();
                int intAge = Integer.parseInt(stringAge);

                String sql = "UPDATE user_info SET name ='" + val2 +"', age ='" 
                        + intAge + "', surname ='" + val3 + "', gender ='" 
                        + gender + "', department = '" + val4 + "', shift ='" 
                        + val5 + "', emploee_egp ='" + val6 + "', division ='" 
                        + val7 +"' WHERE id ='" + val1 +"'";

                pst = conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Successfully Updated!");

            } catch (HeadlessException | NumberFormatException | SQLException e) {

                JOptionPane.showMessageDialog(null, e);

            }
            
            try {
            
            
            File update_image  = new File(filename);
            FileInputStream finputs = new FileInputStream(update_image);
            byte[] image = new byte[(int) update_image.length()];
            finputs.read(image);
            
            String sql10 = "update user_info SET image = ? where id = '" + val1 + "' ";
            
            pst = conn.prepareStatement(sql10);
            pst.setBytes(1, image);
            pst.executeUpdate();
            
            rs.close();
            pst.close();
            
        } catch (IOException | SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
            
            finally {

              try {

                  rs.close();
                  pst.close();

              } catch(SQLException e) {

                }
            }
            
        Update();
        
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       
        txt_id.setText("");
        txt_name.setText("");
        txt_surname.setText("");
        txt_department.setText("");
        txt_shift.setText("");
        txt_gp.setText("");
        txt_division.setText("");
        txt_count.setText("");
        txt_search.setText(null);
        
        buttonGroup1.clearSelection();
        
        c_age.setSelectedItem("Select");
        
        ImageIcon icon = new ImageIcon("./images/img.png");
        image.setIcon(icon);
        
        btn_attach.removeAll();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        try {
            
            String sql = "SELECT count(age) from user_info";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                
                String sum = rs.getString("count(age)");
                txt_count.setText(sum);
                txt_count.setBackground(Color.lightGray);
                
            }
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_btn_showActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
      
        try {
            
            String sql = "SELECT * FROM user_info WHERE name = ?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());
            rs = pst.executeQuery();
            
            if (rs.next()) {
                
                String add1 = rs.getString("id");
                txt_id.setText(add1);
                
                String add2 = rs.getString("name");
                txt_name.setText(add2);
                
                String add3 = rs.getString("surname");
                txt_surname.setText(add3);
                
                String add4 = rs.getString("department");
                txt_department.setText(add4);
                
                String add5 = rs.getString("shift");
                txt_shift.setText(add5);
                
                String add6 = rs.getString("emploee_egp");
                txt_gp.setText(add6);
                
                String add7 = rs.getString("division");
                txt_division.setText(add7);
                
                String add9 = rs.getString("gender");
                if(add9.equals("Male")) {

                this.setMaleGender();

                } else {
                    
                this.setFemaleGender();
                   
                } 
                
                String add10 = rs.getString("age");
                c_age.setSelectedItem(add10);
                
                byte[] image_search_show = rs.getBytes("image");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image_search_show).getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH));
                image.setIcon(imageIcon);
                
            }
            
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        finally {

            try {
                
                rs.close();
                pst.close();
                
            } catch(SQLException e) {

              }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
    
        this.setMaleGender();
        
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        
        this.setFemaleGender(); 
        
    }//GEN-LAST:event_r_femaleActionPerformed

    private void c_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ageActionPerformed

    }//GEN-LAST:event_c_ageActionPerformed

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed

        if (txt_name.getText().isEmpty()) {
        
            txt_name.requestFocus();
            
        } else {
            
            int key = evt.getKeyCode();
            
            if (key == 10) {
                
                txt_surname.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_surnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_surnameKeyPressed
        
        if (txt_surname.getText().isEmpty()) {
        
            txt_surname.requestFocus();
            
        } else {
            
            int key = evt.getKeyCode();
            
            if (key == 10) {
                
                c_age.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txt_surnameKeyPressed

    private void txt_departmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_departmentKeyPressed
        
        if (txt_department.getText().isEmpty()) {
        
            txt_department.requestFocus();
            
        } else {
            
            int key = evt.getKeyCode();
            
            if (key == 10) {
                
                txt_shift.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txt_departmentKeyPressed

    private void txt_shiftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_shiftKeyPressed
        
        if (txt_shift.getText().isEmpty()) {
        
            txt_shift.requestFocus();
            
        } else {
            
            int key = evt.getKeyCode();
            
            if (key == 10) {
                
                txt_gp.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txt_shiftKeyPressed

    private void txt_gpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gpKeyPressed
        
        if (txt_gp.getText().isEmpty()) {
        
            txt_gp.requestFocus();
            
        } else {
            
            int key = evt.getKeyCode();
            
            if (key == 10) {
                
                txt_division.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txt_gpKeyPressed

    private void txt_divisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_divisionKeyPressed
        
        if (txt_division.getText().isEmpty()) {
        
            txt_division.requestFocus();
            
        } else {
            
            int key = evt.getKeyCode();
            
            if (key == 10) {
                
                btn_attach.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txt_divisionKeyPressed

    private void txt_shiftKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_shiftKeyTyped
        
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            
            getToolkit().beep();
            evt.consume();
            
        }
    }//GEN-LAST:event_txt_shiftKeyTyped

    private void txt_gpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gpKeyTyped
            
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            
            getToolkit().beep();
            evt.consume();
            
        }
    }//GEN-LAST:event_txt_gpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attach;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_show;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> c_age;
    private javax.swing.JLabel image;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_division;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_gp;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_persons;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_shift;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel lbl_welcome1;
    private javax.swing.JMenu menu_date;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuItem menu_item_exit;
    private javax.swing.JMenuItem menu_item_faq;
    private javax.swing.JMenu menu_time;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_count;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_division;
    private javax.swing.JTextField txt_gp;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_shift;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
